# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Shop(object):
    def setupUi(self, Shop):
        Shop.setObjectName("Shop")
        Shop.resize(1366, 768)
        Shop.setStyleSheet("QMainWindow {\n"
"    background-color: #F0F0F0;\n"
"    border: none;\n"
"}\n"
"\n"
"QWidget#catalogWidget {\n"
"    border: 2px solid #654321;\n"
"    border-radius: 0px;\n"
"    background-color: #F5F5DC;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #654321;\n"
"    color: white;\n"
"    font-weight: normal;\n"
"    padding: 6px;\n"
"    border: 1px solid #654321;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QTreeWidget::item {\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QTreeWidget::item:hover {\n"
"    background-color: #e0d5c3;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QTreeWidget::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1px solid #654321;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(Shop)
        self.centralwidget.setStyleSheet("QMainWindow {\n"
"    background-color:#F5F5DC;\n"
"    border: 1px solid #D2B48C;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(11, 11, 1344, 746))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageSignIn = QtWidgets.QWidget()
        self.pageSignIn.setObjectName("pageSignIn")
        self.label_signin = QtWidgets.QLabel(self.pageSignIn)
        self.label_signin.setGeometry(QtCore.QRect(530, 60, 291, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_signin.setFont(font)
        self.label_signin.setAlignment(QtCore.Qt.AlignCenter)
        self.label_signin.setObjectName("label_signin")
        self.lineEdit_phone = QtWidgets.QLineEdit(self.pageSignIn)
        self.lineEdit_phone.setGeometry(QtCore.QRect(490, 230, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_phone.setFont(font)
        self.lineEdit_phone.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #8B4513;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    background-color: #F5F5F5;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(51, 51, 51, 0.5);\n"
"    font-style: italic;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #A0522D;\n"
"    background-color: #FFFFFF;\n"
"}")
        self.lineEdit_phone.setObjectName("lineEdit_phone")
        self.btn_signin = QtWidgets.QPushButton(self.pageSignIn)
        self.btn_signin.setGeometry(QtCore.QRect(490, 370, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_signin.setFont(font)
        self.btn_signin.setStyleSheet("QPushButton:enabled {\n"
"    background-color: #654321;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgba(160, 82, 45, 0.5);\n"
"    color: rgba(255, 255, 255, 0.5);\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.btn_signin.setObjectName("btn_signin")
        self.lineEdit_psw = QtWidgets.QLineEdit(self.pageSignIn)
        self.lineEdit_psw.setGeometry(QtCore.QRect(490, 300, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_psw.setFont(font)
        self.lineEdit_psw.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #8B4513;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    background-color: #F5F5F5;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(51, 51, 51, 0.5);\n"
"    font-style: italic;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #A0522D;\n"
"    background-color: #FFFFFF;\n"
"}")
        self.lineEdit_psw.setObjectName("lineEdit_psw")
        self.btn_signup_2 = QtWidgets.QPushButton(self.pageSignIn)
        self.btn_signup_2.setGeometry(QtCore.QRect(560, 480, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_signup_2.setFont(font)
        self.btn_signup_2.setStyleSheet("QPushButton:enabled {\n"
"    background-color: #654321;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgba(160, 82, 45, 0.5);\n"
"    color: rgba(255, 255, 255, 0.5);\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.btn_signup_2.setObjectName("btn_signup_2")
        self.stackedWidget.addWidget(self.pageSignIn)
        self.pageSignUp = QtWidgets.QWidget()
        self.pageSignUp.setObjectName("pageSignUp")
        self.lineEdit_psw_2 = QtWidgets.QLineEdit(self.pageSignUp)
        self.lineEdit_psw_2.setEnabled(True)
        self.lineEdit_psw_2.setGeometry(QtCore.QRect(490, 270, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_psw_2.setFont(font)
        self.lineEdit_psw_2.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #8B4513;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    background-color: #F5F5F5;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(51, 51, 51, 0.5);\n"
"    font-style: italic;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #A0522D;\n"
"    background-color: #FFFFFF;\n"
"}")
        self.lineEdit_psw_2.setObjectName("lineEdit_psw_2")
        self.lineEdit_phone_2 = QtWidgets.QLineEdit(self.pageSignUp)
        self.lineEdit_phone_2.setEnabled(True)
        self.lineEdit_phone_2.setGeometry(QtCore.QRect(490, 410, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_phone_2.setFont(font)
        self.lineEdit_phone_2.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #8B4513;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    background-color: #F5F5F5;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(51, 51, 51, 0.5);\n"
"    font-style: italic;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #A0522D;\n"
"    background-color: #FFFFFF;\n"
"}")
        self.lineEdit_phone_2.setObjectName("lineEdit_phone_2")
        self.lineEdit_email = QtWidgets.QLineEdit(self.pageSignUp)
        self.lineEdit_email.setEnabled(True)
        self.lineEdit_email.setGeometry(QtCore.QRect(490, 340, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_email.setFont(font)
        self.lineEdit_email.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #8B4513;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    background-color: #F5F5F5;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(51, 51, 51, 0.5);\n"
"    font-style: italic;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #A0522D;\n"
"    background-color: #FFFFFF;\n"
"}")
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.label_signup = QtWidgets.QLabel(self.pageSignUp)
        self.label_signup.setGeometry(QtCore.QRect(530, 30, 291, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_signup.setFont(font)
        self.label_signup.setAlignment(QtCore.Qt.AlignCenter)
        self.label_signup.setObjectName("label_signup")
        self.lineEdit_name = QtWidgets.QLineEdit(self.pageSignUp)
        self.lineEdit_name.setEnabled(True)
        self.lineEdit_name.setGeometry(QtCore.QRect(490, 200, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #8B4513;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    background-color: #F5F5F5;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(51, 51, 51, 0.5);\n"
"    font-style: italic;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #A0522D;\n"
"    background-color: #FFFFFF;\n"
"}")
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.checkBox = QtWidgets.QCheckBox(self.pageSignUp)
        self.checkBox.setGeometry(QtCore.QRect(510, 480, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.checkBox.setFont(font)
        self.checkBox.setTabletTracking(False)
        self.checkBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.checkBox.setAcceptDrops(False)
        self.checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox.setChecked(False)
        self.checkBox.setAutoRepeat(False)
        self.checkBox.setAutoExclusive(False)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.btn_signup = QtWidgets.QPushButton(self.pageSignUp)
        self.btn_signup.setGeometry(QtCore.QRect(490, 510, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_signup.setFont(font)
        self.btn_signup.setStyleSheet("QPushButton:enabled {\n"
"    background-color: #654321;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgba(160, 82, 45, 0.5);\n"
"    color: rgba(255, 255, 255, 0.5);\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.btn_signup.setObjectName("btn_signup")
        self.btn_signin_2 = QtWidgets.QPushButton(self.pageSignUp)
        self.btn_signin_2.setGeometry(QtCore.QRect(560, 590, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_signin_2.setFont(font)
        self.btn_signin_2.setStyleSheet("QPushButton:enabled {\n"
"    background-color: #654321;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgba(160, 82, 45, 0.5);\n"
"    color: rgba(255, 255, 255, 0.5);\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.btn_signin_2.setObjectName("btn_signin_2")
        self.stackedWidget.addWidget(self.pageSignUp)
        self.page_MainShop = QtWidgets.QWidget()
        self.page_MainShop.setObjectName("page_MainShop")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.page_MainShop)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1341, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_technolite = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_technolite.setFont(font)
        self.label_technolite.setAlignment(QtCore.Qt.AlignCenter)
        self.label_technolite.setObjectName("label_technolite")
        self.horizontalLayout.addWidget(self.label_technolite)
        self.lineEdit_search = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_search.setMinimumSize(QtCore.QSize(300, 30))
        self.lineEdit_search.setMaximumSize(QtCore.QSize(700, 16777215))
        self.lineEdit_search.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #8B4513;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    background-color: #F5F5F5;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(51, 51, 51, 0.5);\n"
"    font-style: italic;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #A0522D;\n"
"    background-color: #FFFFFF;\n"
"}")
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.horizontalLayout.addWidget(self.lineEdit_search)
        self.btn_orders = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_orders.setMinimumSize(QtCore.QSize(150, 30))
        self.btn_orders.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btn_orders.setStyleSheet("QPushButton:enabled {\n"
"    background-color: #654321;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgba(160, 82, 45, 0.5);\n"
"    color: rgba(255, 255, 255, 0.5);\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.btn_orders.setObjectName("btn_orders")
        self.horizontalLayout.addWidget(self.btn_orders)
        self.btn_cart = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_cart.setMinimumSize(QtCore.QSize(150, 30))
        self.btn_cart.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btn_cart.setStyleSheet("QPushButton:enabled {\n"
"    background-color: #654321;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgba(160, 82, 45, 0.5);\n"
"    color: rgba(255, 255, 255, 0.5);\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.btn_cart.setObjectName("btn_cart")
        self.horizontalLayout.addWidget(self.btn_cart)
        self.btn_pers_acc = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_pers_acc.setMinimumSize(QtCore.QSize(150, 30))
        self.btn_pers_acc.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btn_pers_acc.setStyleSheet("QPushButton:enabled {\n"
"    background-color: #654321;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgba(160, 82, 45, 0.5);\n"
"    color: rgba(255, 255, 255, 0.5);\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.btn_pers_acc.setObjectName("btn_pers_acc")
        self.horizontalLayout.addWidget(self.btn_pers_acc)
        self.widget = QtWidgets.QWidget(self.page_MainShop)
        self.widget.setGeometry(QtCore.QRect(10, 80, 341, 651))
        self.widget.setStyleSheet("QWidget {\n"
"    border: 2px solid #654321;\n"
"    border-radius: 8px;\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 341, 651))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_catalog = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_catalog.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_catalog.setObjectName("verticalLayout_catalog")
        self.treeWidget_category = QtWidgets.QTreeWidget(self.verticalLayoutWidget)
        self.treeWidget_category.setStyleSheet("\n"
"QTreeWidget::item:hover {\n"
"    background-color: #e0d5c3;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QTreeWidget::item:selected {\n"
"    background-color: #d2b48c;\n"
"    color: black;\n"
"}\n"
"\n"
"QTreeWidget::item:selected:active {\n"
"    border: none;\n"
"}\n"
"\n"
"QTreeWidget::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1px solid #654321;\n"
"}")
        self.treeWidget_category.setHeaderHidden(False)
        self.treeWidget_category.setObjectName("treeWidget_category")
        self.treeWidget_category.headerItem().setText(0, "Каталог")
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.treeWidget_category.headerItem().setFont(0, font)
        self.verticalLayout_catalog.addWidget(self.treeWidget_category)
        self.scrollAreaProducts = QtWidgets.QScrollArea(self.page_MainShop)
        self.scrollAreaProducts.setGeometry(QtCore.QRect(369, 86, 971, 641))
        self.scrollAreaProducts.setWidgetResizable(True)
        self.scrollAreaProducts.setObjectName("scrollAreaProducts")
        self.scrollArea = QtWidgets.QWidget()
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 969, 639))
        self.scrollArea.setObjectName("scrollArea")
        self.productGridWidget = QtWidgets.QWidget(self.scrollArea)
        self.productGridWidget.setGeometry(QtCore.QRect(-1, -1, 971, 641))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productGridWidget.sizePolicy().hasHeightForWidth())
        self.productGridWidget.setSizePolicy(sizePolicy)
        self.productGridWidget.setObjectName("productGridWidget")
        self.scrollAreaProducts.setWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.page_MainShop)
        self.page_orders = QtWidgets.QWidget()
        self.page_orders.setObjectName("page_orders")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.page_orders)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(30, 130, 1291, 421))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_orders = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_orders.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_orders.setObjectName("verticalLayout_orders")
        self.tableWidget_orders = QtWidgets.QTableWidget(self.verticalLayoutWidget_3)
        self.tableWidget_orders.setObjectName("tableWidget_orders")
        self.tableWidget_orders.setColumnCount(6)
        self.tableWidget_orders.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_orders.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_orders.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_orders.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_orders.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_orders.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_orders.setHorizontalHeaderItem(5, item)
        self.tableWidget_orders.horizontalHeader().setVisible(False)
        self.tableWidget_orders.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_orders.horizontalHeader().setDefaultSectionSize(300)
        self.tableWidget_orders.horizontalHeader().setHighlightSections(True)
        self.tableWidget_orders.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget_orders.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_orders.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_orders.addWidget(self.tableWidget_orders)
        self.label_orders = QtWidgets.QLabel(self.page_orders)
        self.label_orders.setGeometry(QtCore.QRect(530, 20, 291, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_orders.setFont(font)
        self.label_orders.setStyleSheet("color: #654321;\n"
"")
        self.label_orders.setAlignment(QtCore.Qt.AlignCenter)
        self.label_orders.setObjectName("label_orders")
        self.btn_orders_shop = QtWidgets.QPushButton(self.page_orders)
        self.btn_orders_shop.setGeometry(QtCore.QRect(560, 630, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_orders_shop.setFont(font)
        self.btn_orders_shop.setStyleSheet("QPushButton:enabled {\n"
"    background-color: #654321;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgba(160, 82, 45, 0.5);\n"
"    color: rgba(255, 255, 255, 0.5);\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.btn_orders_shop.setObjectName("btn_orders_shop")
        self.stackedWidget.addWidget(self.page_orders)
        self.page_cart = QtWidgets.QWidget()
        self.page_cart.setObjectName("page_cart")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.page_cart)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 130, 1291, 301))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_cart = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_cart.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_cart.setObjectName("verticalLayout_cart")
        self.tableWidget_cart = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.tableWidget_cart.setAutoScroll(True)
        self.tableWidget_cart.setTabKeyNavigation(True)
        self.tableWidget_cart.setProperty("showDropIndicator", True)
        self.tableWidget_cart.setObjectName("tableWidget_cart")
        self.tableWidget_cart.setColumnCount(4)
        self.tableWidget_cart.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_cart.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_cart.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_cart.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_cart.setHorizontalHeaderItem(3, item)
        self.tableWidget_cart.horizontalHeader().setVisible(False)
        self.tableWidget_cart.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_cart.horizontalHeader().setDefaultSectionSize(321)
        self.tableWidget_cart.horizontalHeader().setHighlightSections(True)
        self.tableWidget_cart.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget_cart.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_cart.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_cart.verticalHeader().setVisible(False)
        self.verticalLayout_cart.addWidget(self.tableWidget_cart)
        self.label_cart = QtWidgets.QLabel(self.page_cart)
        self.label_cart.setGeometry(QtCore.QRect(530, 20, 291, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_cart.setFont(font)
        self.label_cart.setStyleSheet("color: #654321;\n"
"")
        self.label_cart.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cart.setObjectName("label_cart")
        self.label = QtWidgets.QLabel(self.page_cart)
        self.label.setGeometry(QtCore.QRect(40, 450, 561, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #654321;")
        self.label.setObjectName("label")
        self.btn_orders_cart = QtWidgets.QPushButton(self.page_cart)
        self.btn_orders_cart.setGeometry(QtCore.QRect(410, 570, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_orders_cart.setFont(font)
        self.btn_orders_cart.setStyleSheet("QPushButton:enabled {\n"
"    background-color: #654321;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgba(160, 82, 45, 0.5);\n"
"    color: rgba(255, 255, 255, 0.5);\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.btn_orders_cart.setObjectName("btn_orders_cart")
        self.btn_clear_cart = QtWidgets.QPushButton(self.page_cart)
        self.btn_clear_cart.setGeometry(QtCore.QRect(720, 570, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_clear_cart.setFont(font)
        self.btn_clear_cart.setStyleSheet("QPushButton:enabled {\n"
"    background-color: #654321;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgba(160, 82, 45, 0.5);\n"
"    color: rgba(255, 255, 255, 0.5);\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.btn_clear_cart.setObjectName("btn_clear_cart")
        self.stackedWidget.addWidget(self.page_cart)
        self.page_pers_acc = QtWidgets.QWidget()
        self.page_pers_acc.setObjectName("page_pers_acc")
        self.label_pers_acc = QtWidgets.QLabel(self.page_pers_acc)
        self.label_pers_acc.setGeometry(QtCore.QRect(510, 20, 331, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_pers_acc.setFont(font)
        self.label_pers_acc.setStyleSheet("color: #654321;\n"
"")
        self.label_pers_acc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pers_acc.setObjectName("label_pers_acc")
        self.label_name = QtWidgets.QLabel(self.page_pers_acc)
        self.label_name.setGeometry(QtCore.QRect(390, 200, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_name.setFont(font)
        self.label_name.setStyleSheet("color: #654321;\n"
"")
        self.label_name.setObjectName("label_name")
        self.label_email = QtWidgets.QLabel(self.page_pers_acc)
        self.label_email.setGeometry(QtCore.QRect(390, 280, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_email.setFont(font)
        self.label_email.setStyleSheet("color: #654321;\n"
"")
        self.label_email.setObjectName("label_email")
        self.label_phone = QtWidgets.QLabel(self.page_pers_acc)
        self.label_phone.setGeometry(QtCore.QRect(390, 360, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_phone.setFont(font)
        self.label_phone.setStyleSheet("color: #654321;\n"
"")
        self.label_phone.setObjectName("label_phone")
        self.lineEdit_name_2 = QtWidgets.QLineEdit(self.page_pers_acc)
        self.lineEdit_name_2.setGeometry(QtCore.QRect(490, 190, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_name_2.setFont(font)
        self.lineEdit_name_2.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #8B4513;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    background-color: #F5F5F5;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(51, 51, 51, 0.5);\n"
"    font-style: italic;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #A0522D;\n"
"    background-color: #FFFFFF;\n"
"}")
        self.lineEdit_name_2.setReadOnly(True)
        self.lineEdit_name_2.setPlaceholderText("")
        self.lineEdit_name_2.setObjectName("lineEdit_name_2")
        self.lineEdit_email_2 = QtWidgets.QLineEdit(self.page_pers_acc)
        self.lineEdit_email_2.setGeometry(QtCore.QRect(490, 270, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_email_2.setFont(font)
        self.lineEdit_email_2.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #8B4513;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    background-color: #F5F5F5;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(51, 51, 51, 0.5);\n"
"    font-style: italic;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #A0522D;\n"
"    background-color: #FFFFFF;\n"
"}")
        self.lineEdit_email_2.setReadOnly(True)
        self.lineEdit_email_2.setPlaceholderText("")
        self.lineEdit_email_2.setObjectName("lineEdit_email_2")
        self.lineEdit_phone_3 = QtWidgets.QLineEdit(self.page_pers_acc)
        self.lineEdit_phone_3.setGeometry(QtCore.QRect(490, 350, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_phone_3.setFont(font)
        self.lineEdit_phone_3.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #8B4513;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    background-color: #F5F5F5;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(51, 51, 51, 0.5);\n"
"    font-style: italic;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #A0522D;\n"
"    background-color: #FFFFFF;\n"
"}")
        self.lineEdit_phone_3.setReadOnly(True)
        self.lineEdit_phone_3.setPlaceholderText("")
        self.lineEdit_phone_3.setObjectName("lineEdit_phone_3")
        self.btn_pers_acc_shop = QtWidgets.QPushButton(self.page_pers_acc)
        self.btn_pers_acc_shop.setGeometry(QtCore.QRect(570, 590, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_pers_acc_shop.setFont(font)
        self.btn_pers_acc_shop.setStyleSheet("QPushButton:enabled {\n"
"    background-color: #654321;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgba(160, 82, 45, 0.5);\n"
"    color: rgba(255, 255, 255, 0.5);\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.btn_pers_acc_shop.setObjectName("btn_pers_acc_shop")
        self.stackedWidget.addWidget(self.page_pers_acc)
        self.page_product = QtWidgets.QWidget()
        self.page_product.setObjectName("page_product")
        self.label_image = QtWidgets.QLabel(self.page_product)
        self.label_image.setGeometry(QtCore.QRect(20, 40, 341, 291))
        self.label_image.setScaledContents(True)
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setObjectName("label_image")
        self.label_name_product = QtWidgets.QLabel(self.page_product)
        self.label_name_product.setGeometry(QtCore.QRect(570, 40, 711, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_name_product.setFont(font)
        self.label_name_product.setStyleSheet("color: #654321;\n"
"")
        self.label_name_product.setText("")
        self.label_name_product.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name_product.setObjectName("label_name_product")
        self.label_price = QtWidgets.QLabel(self.page_product)
        self.label_price.setGeometry(QtCore.QRect(600, 150, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_price.setFont(font)
        self.label_price.setStyleSheet("color: #654321;\n"
"")
        self.label_price.setObjectName("label_price")
        self.label_input_price = QtWidgets.QLabel(self.page_product)
        self.label_input_price.setGeometry(QtCore.QRect(740, 150, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_input_price.setFont(font)
        self.label_input_price.setStyleSheet("color: #654321;\n"
"")
        self.label_input_price.setText("")
        self.label_input_price.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_price.setObjectName("label_input_price")
        self.label_price_2 = QtWidgets.QLabel(self.page_product)
        self.label_price_2.setGeometry(QtCore.QRect(600, 220, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_price_2.setFont(font)
        self.label_price_2.setStyleSheet("color: #654321;\n"
"")
        self.label_price_2.setObjectName("label_price_2")
        self.label_2 = QtWidgets.QLabel(self.page_product)
        self.label_2.setGeometry(QtCore.QRect(740, 230, 561, 181))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #654321;\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.page_product)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 380, 671, 351))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget_4)
        self.tabWidget.setStyleSheet("QTabWidget {\n"
"    background-color: #f5f5f5;  /* Фоновый цвет для всего QTabWidget */\n"
"    border: 1px solid #654321;   /* Темная граница вокруг QTabWidget */\n"
"    border-radius: 5px;  /* Закругленные углы */\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;  /* Убираем лишнюю границу вокруг вкладок */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: #a68b6a;  /* Цвет фона для вкладки по умолчанию */\n"
"    color: #333333;  /* Цвет текста вкладки по умолчанию */\n"
"    padding: 10px;\n"
"    border: 1px solid #654321;   /* Граница вокруг вкладки */\n"
"    border-radius: 5px;   /* Закругленные углы для вкладки */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color: #8c6f50;  /* Цвет фона при наведении (темнее) */\n"
"    color: black;  /* Цвет текста при наведении */\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: #654321;  /* Цвет фона для выбранной вкладки */\n"
"    color: white;  /* Цвет текста для выбранной вкладки */\n"
"}\n"
"\n"
"QTabBar::tab:selected:active {\n"
"    border: 2px solid #654321;  /* Более выраженная граница для активной вкладки */\n"
"}\n"
"\n"
"QTabBar::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1px solid #654321;  /* Темная граница для индикатора */\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_characteristic = QtWidgets.QWidget()
        self.tab_characteristic.setObjectName("tab_characteristic")
        self.tableWidget_tab = QtWidgets.QTableWidget(self.tab_characteristic)
        self.tableWidget_tab.setGeometry(QtCore.QRect(-5, 1, 681, 311))
        self.tableWidget_tab.setObjectName("tableWidget_tab")
        self.tableWidget_tab.setColumnCount(2)
        self.tableWidget_tab.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tab.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_tab.setHorizontalHeaderItem(1, item)
        self.tableWidget_tab.horizontalHeader().setDefaultSectionSize(325)
        self.tableWidget_tab.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_tab.horizontalHeader().setStretchLastSection(True)
        self.tabWidget.addTab(self.tab_characteristic, "")
        self.tab_reviews = QtWidgets.QWidget()
        self.tab_reviews.setObjectName("tab_reviews")
        self.label_rating = QtWidgets.QLabel(self.tab_reviews)
        self.label_rating.setGeometry(QtCore.QRect(10, 20, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_rating.setFont(font)
        self.label_rating.setStyleSheet("color: #654321;\n"
"")
        self.label_rating.setObjectName("label_rating")
        self.spinBox_rating = QtWidgets.QSpinBox(self.tab_reviews)
        self.spinBox_rating.setGeometry(QtCore.QRect(260, 20, 261, 31))
        self.spinBox_rating.setStyleSheet("QSpinBox {\n"
"    border: 1px solid #654321;  /* Темно-коричневая граница */\n"
"    border-radius: 5px;         /* Закругленные углы */\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"    background-color: #8c6f4f;  /* Светло-коричневая кнопка */\n"
"    border: none;               /* Без рамки вокруг кнопки */\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"    background-color: #8c6f4f;  /* Светло-коричневая кнопка */\n"
"    border: none;               /* Без рамки вокруг кнопки */\n"
"}\n"
"\n"
"QSpinBox::up-button:hover,\n"
"QSpinBox::down-button:hover {\n"
"    background-color: #a68b6a;  /* Немного более темный коричневый при наведении */\n"
"}\n"
"")
        self.spinBox_rating.setObjectName("spinBox_rating")
        self.label_description = QtWidgets.QLabel(self.tab_reviews)
        self.label_description.setGeometry(QtCore.QRect(10, 70, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_description.setFont(font)
        self.label_description.setStyleSheet("color: #654321;\n"
"")
        self.label_description.setObjectName("label_description")
        self.lineEdit_description = QtWidgets.QLineEdit(self.tab_reviews)
        self.lineEdit_description.setGeometry(QtCore.QRect(10, 110, 501, 191))
        self.lineEdit_description.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #8B4513;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    background-color: #F5F5F5;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(51, 51, 51, 0.5);\n"
"    font-style: italic;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #A0522D;\n"
"    background-color: #FFFFFF;\n"
"}")
        self.lineEdit_description.setObjectName("lineEdit_description")
        self.btn_submit = QtWidgets.QPushButton(self.tab_reviews)
        self.btn_submit.setGeometry(QtCore.QRect(530, 260, 131, 41))
        self.btn_submit.setStyleSheet("QPushButton:enabled {\n"
"    background-color: #654321;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgba(160, 82, 45, 0.5);\n"
"    color: rgba(255, 255, 255, 0.5);\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.btn_submit.setObjectName("btn_submit")
        self.tabWidget.addTab(self.tab_reviews, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.stackedWidget.addWidget(self.page_product)
        Shop.setCentralWidget(self.centralwidget)

        self.retranslateUi(Shop)
        self.stackedWidget.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Shop)

    def retranslateUi(self, Shop):
        _translate = QtCore.QCoreApplication.translate
        Shop.setWindowTitle(_translate("Shop", "Shop"))
        self.label_signin.setText(_translate("Shop", "Вход"))
        self.lineEdit_phone.setPlaceholderText(_translate("Shop", "Введите номер телефона"))
        self.btn_signin.setText(_translate("Shop", "Войти"))
        self.lineEdit_psw.setPlaceholderText(_translate("Shop", "Введите пароль"))
        self.btn_signup_2.setText(_translate("Shop", "Регистрация"))
        self.lineEdit_psw_2.setPlaceholderText(_translate("Shop", "Придумайте пароль"))
        self.lineEdit_phone_2.setPlaceholderText(_translate("Shop", "Введите номер телефона"))
        self.lineEdit_email.setPlaceholderText(_translate("Shop", "Введите email"))
        self.label_signup.setText(_translate("Shop", "Регистрация"))
        self.lineEdit_name.setPlaceholderText(_translate("Shop", "Введите имя"))
        self.checkBox.setText(_translate("Shop", "Даю согласие на обработку персональных данных"))
        self.btn_signup.setText(_translate("Shop", "Зарегистрироваться"))
        self.btn_signin_2.setText(_translate("Shop", "Войти"))
        self.label_technolite.setText(_translate("Shop", "TechnoLite"))
        self.lineEdit_search.setPlaceholderText(_translate("Shop", "Поиск товаров"))
        self.btn_orders.setText(_translate("Shop", "Заказы"))
        self.btn_cart.setText(_translate("Shop", "Корзина"))
        self.btn_pers_acc.setText(_translate("Shop", "Личный кабинет"))
        item = self.tableWidget_orders.horizontalHeaderItem(0)
        item.setText(_translate("Shop", "Номер заказа"))
        item = self.tableWidget_orders.horizontalHeaderItem(1)
        item.setText(_translate("Shop", "Дата"))
        item = self.tableWidget_orders.horizontalHeaderItem(2)
        item.setText(_translate("Shop", "Сумма"))
        item = self.tableWidget_orders.horizontalHeaderItem(3)
        item.setText(_translate("Shop", "Адрес"))
        item = self.tableWidget_orders.horizontalHeaderItem(4)
        item.setText(_translate("Shop", "Статус заказа"))
        item = self.tableWidget_orders.horizontalHeaderItem(5)
        item.setText(_translate("Shop", "Статус оплаты"))
        self.label_orders.setText(_translate("Shop", "Заказы"))
        self.btn_orders_shop.setText(_translate("Shop", "Вернуться в магазин"))
        item = self.tableWidget_cart.horizontalHeaderItem(0)
        item.setText(_translate("Shop", "Название"))
        item = self.tableWidget_cart.horizontalHeaderItem(1)
        item.setText(_translate("Shop", "Цена"))
        item = self.tableWidget_cart.horizontalHeaderItem(2)
        item.setText(_translate("Shop", "Количество"))
        item = self.tableWidget_cart.horizontalHeaderItem(3)
        item.setText(_translate("Shop", "Итого"))
        self.label_cart.setText(_translate("Shop", "Корзина"))
        self.label.setText(_translate("Shop", "Общая сумма товаров в корзине: 0.00 руб."))
        self.btn_orders_cart.setText(_translate("Shop", "Оформить заказ"))
        self.btn_clear_cart.setText(_translate("Shop", "Очистить корзину"))
        self.label_pers_acc.setText(_translate("Shop", "Личный кабинет"))
        self.label_name.setText(_translate("Shop", "Имя"))
        self.label_email.setText(_translate("Shop", "Email"))
        self.label_phone.setText(_translate("Shop", "Телефон"))
        self.btn_pers_acc_shop.setText(_translate("Shop", "В магазин"))
        self.label_image.setText(_translate("Shop", "Фото"))
        self.label_price.setText(_translate("Shop", "Цена:"))
        self.label_price_2.setText(_translate("Shop", "Описание:"))
        item = self.tableWidget_tab.horizontalHeaderItem(0)
        item.setText(_translate("Shop", "Характеристика"))
        item = self.tableWidget_tab.horizontalHeaderItem(1)
        item.setText(_translate("Shop", "Значение"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_characteristic), _translate("Shop", "Характеристики"))
        self.label_rating.setText(_translate("Shop", "Оценка товара (от 1 до 5):"))
        self.label_description.setText(_translate("Shop", "Описание:"))
        self.btn_submit.setText(_translate("Shop", "Отправить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_reviews), _translate("Shop", "Отзывы"))
